### PR TITLE
Patch bridgetown compatibility with view_component 3.9.0+

### LINKED ISSUE #3145: Bridgetown fails to build against view_component 3.9
The bridgetown project fails to build when updated to view_component 3.9. We should investigate the cause and potentially create a reduced test case to confirm if the issue can be replicated using a fresh bridgetown install.

Related issue: https://github.com/bridgetownrb/bridgetown-view-component/issues/8

### PR DESCRIPTION
**Pull request by davidrapson**
ViewComponent 3.9+ introduced a change which depends on there being an active Rails request or controller in order to conditionally escape HTML. This causes an issue when run in bridgetown as there's no request and we're always rendering static html.

Whilst this is monkey patching an internal method this feels like the least worst approach as it removes just the single check that's dependent on the request whilst still keeping the underlying escaping.

(Temporarily) fixes #3145. Related issue: https://github.com/bridgetownrb/bridgetown-view-component/issues/8

### CODE REVIEW

File: design-system-docs/Gemfile [hunk 1]
```diff
@@ -13,9 +13,6 @@ gem "puma"
 
 gem "citizens_advice_components", path: "../engine"
 
-# https://github.com/citizensadvice/design-system/issues/3145
-gem "view_component", "3.8.0"
```
Comment (leeky) [inline design-system-docs/Gemfile:17]: Should the PR include a note for why you've removed the `view_component` dependency? Is `citizens_advice_components` now using 3.9.0+ internally?

File: design-system-docs/plugins/builders/cads_builder.rb [hunk 2]
```diff
@@ -13,6 +13,27 @@
 
 Time.zone = "London"
 
+# ViewComponent 3.9+ introduced a change which depends on there being an active Rails
```
Comment (leeky) [inline design-system-docs/plugins/builders/cads_builder.rb:16]: 👍

**Review by leeky — APPROVED** [review]
LGTM! :shipit:

File: design-system-docs/Gemfile (hunk 1 above)
Comment (davidrapson) [reply design-system-docs/Gemfile:17]: It will use the latest version of view component (we technically support both 2.x and 3.x) but/and yep let me add a note in the commit and PR description.
